# Generated by Django 5.1.5 on 2025-01-31 13:57

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('Sand', 'Sand'), ('Cement', 'Cement'), ('Bricks', 'Bricks'), ('Nail', 'Nail'), ('Water', 'Water'), ('Stone Aggregates', 'Stone Aggregates')], max_length=27, unique=True)),
                ('quantity', models.IntegerField()),
                ('used', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuzimbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('sirname', models.CharField(max_length=50)),
                ('tellNo', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('jobtitle', models.CharField(choices=[('Porter', 'Porter'), ('Builder', 'Builder'), ('Tracker', 'Tracker'), ('Manager', 'Manager')], max_length=10)),
                ('approved', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='%(app_label)s_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='%(app_label)s_user_permissions_set', to='auth.permission')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2025-01-31')),
                ('dayid', models.CharField(max_length=25, unique=True)),
                ('arrival', models.TimeField()),
                ('depature', models.TimeField()),
                ('jobtitle', models.CharField(max_length=10)),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_attendences', to=settings.AUTH_USER_MODEL)),
                ('tellNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attended_tell_no', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought', models.IntegerField()),
                ('left', models.IntegerField()),
                ('datetime', models.DateField(default='2025-01-31 16:57')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used', models.IntegerField()),
                ('material', models.ForeignKey(choices=[('Sand', 'Sand'), ('Cement', 'Cement'), ('Bricks', 'Bricks'), ('Nail', 'Nail'), ('Water', 'Water'), ('Stone Aggregates', 'Stone Aggregates')], on_delete=django.db.models.deletion.CASCADE, to='api.materials')),
            ],
        ),
    ]
